### ISSUE TITLE
Metas based off title and maybe other options?

### ISSUE THREAD

**Issue by dfcreative** [dominictarr/indexhtmlify#5]
Hi @dominictarr!

The package is sweet!
One suggestion. Is there any sense to include some (optional) [additional metas](https://github.com/joshbuchea/HEAD), based on title or maybe other CLI arguments? That may come handy for retweeting/reposting demos.
Though it will spoil minimalistic approach a bit.

**Comment by dominictarr** [comment]
which metas do you most want? prehaps there is a simple to way add them? to add css, you can do `--style <file.css>` maybe something similar?

**Comment by dfcreative** [comment]
Well if title is provided it can be used for 
```html
<meta name="subject" content="your website's subject">
<meta property="og:title" content="Content Title">
<meta property="og:site_name" content="Site Name">
<meta name="twitter:title" content="Content Title">
<meta itemprop="name" content="Content Title">
```
Usually there also goes _description_ and _preview_ in the same fashion, not sure should it be included or not, but posting a link to the demo with preview/description in twitter, for example, would add thumbnail to the tweet.

**Comment by dominictarr** [comment]
you know, the most unixy way to do this would be to have another program that was `metadataify` or something, and then indexhtmlify would use the output of that.

`browserify index | indexhtmlify --head <(metadataify --title foo)`

etc

`<(command)` takes the stdout of `command` and turns it into a temporary file, which is then passed as an argument.

**Comment by rreusser** [comment]
I've wanted this, so I made a quick first cut at [metadataify](https://github.com/rreusser/metadataify)

Usage is:

```bash
$ cat index.html | metadataify --title "a title" \
    --meta-name og:image="..." \
    --meta-name description="a description"
```

Definitely open to different syntaxes here.

**Comment by dominictarr** [comment]
@rreusser ooh that is nicer than what i suggested actually! I'm gonna add a link to it from indexhtmlify readme

**Comment by dfcreative** [comment]
@rreusser I see you’ve chosen generic approach to the problem of metas, but doesn’t it make remembering all possible metas a bit difficult?
For major part of metas it is enough to know _title_, _description_, _image_, _url_ and maybe _author_. By default it is possible to take `package.json` fields for that, except for the image.

```js
({title, description, url, image, author}) => {
	let pkg = require('./package.json');

	//init defaults
	if (title == null) title = pkg.name;
	if (description == null) description = pkg.description;
	if (url == null) url = pkg.repository.url;
	if (author == null) author = pkg.author;

	return `
	<title>{{ title }}</title>
	<meta name="application-name" content="{{ title }}">
	<meta name="description" content="{{ description }}">
	<meta name="subject" content="{{ description || title }}">
	<meta name="abstract" content="{{ title }}">
	<meta name="url" content="{{ url }}">
	<meta name="author" content="{{ author }}">
	<link rel="canonical" href="{{ url }}">

	<meta property="og:title" content="{{ title }}">
	<meta property="og:image" content="{{ image }}">
	<meta property="og:description" content="{{ description }}">
	<meta property="og:url" content="{{ url }}">
	<meta property="article:author" content="{{ author }}">

	<meta name="twitter:creator" content="{{ author }}">
	<meta name="twitter:url" content="{{ url }}">
	<meta name="twitter:title" content="{{ title }}">
	<meta name="twitter:description" content="{{ description }}">
	<meta name="twitter:image" content="{{ image }}">

	<meta itemprop="name" content="{{ title }}">
	<meta itemprop="description" content="{{ description }}">
	<meta itemprop="image" content="{{ image }}">
	`;
}
```

**Comment by rreusser** [comment]
Ooh. Not a bad idea. Maybe those should be convenience parameters and we can still expose the raw interface.

**Comment by rreusser** [comment]
Okay, I've really updated it. I tried to make it *really* straightforward, then allow increasingly more precise overrides *if* absolutely necessary. Not done and needs some quick tests, but it's not bad, perhaps…

**Comment by rreusser** [comment]
Actually, to keep it simple, when I get a chance I'm gonna go back and remove like 80% of those docs and give people what they need to customize *if* they need to customize.

**Comment by rreusser** [comment]
Okay, finally had a bit of time to clean up and publish to npm. I suspect many, many improvements are possible. PRs welcome. But hopefully it meets the basic need 👍

**Comment by dfcreative** [comment]
Nice, I will give it a try in upcoming demos. Thanks a lot!

**Comment by rreusser** [comment]
@dfcreative: you may also be interested in one more addition to the set of tools: [github-cornerify](https://github.com/rreusser/github-cornerify)

**Comment by dfcreative** [comment]
Oh, sweet, thanks!
Though I tend to use settings-panel with title referring to the source repo, like [here](https://audio-lab.github.io/wavefont/)
